### Application Information ###
name: "matrix_multiplication" # Name of the application from the CSV
description: "Matrix multiplication implementation using CKKS scheme" # Description of the application
title: "matrix_multiplication" # Title to be used in the plot
event_type: "Time" # Event type being esimated

### CSV Paths ###
primitive_benchmarks: "../datasets/amd/primitives/all-primitives-timing-results.csv" # Path to the primitive benchmarks CSV
actual_benchmarks: "../datasets/amd/microbenchmarks/microbenchmark-results.csv" # Path to the actual application CSV for model validation (optional)

### Performance Model Parameters ###
parameters:
  security_standard_level: none
  n: 16
  depth: 10
  num_threads: sweep

### Application Homomorphic Operation Counts ###
operation_counts:
  CKKS_Add: 178
  CKKS_Rotate: 193
  CKKS_Mult: 16
  CKKS_Mult_Plaintext: 32

### Statistical Methods ###
statistic: "median" # Options: median, mean